#!/usr/bin/env python3
"""Build one source-confirmed GXB MID2 ZIP-volume hot update.

Files are collected from backend-local ``local_assets/src_32`` and ``src_64``.
Only sparse operator overrides should be placed there.  The generated one-volume
ZIP is served as ``/updates/<package>.001`` and advertised by MID2 via
``local_assets/update_manifest.json``.

The builder never modifies APK files and never touches the connected device.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import tempfile
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCAL = ROOT / "local_assets"
UPDATES = LOCAL / "updates"
MANIFEST = LOCAL / "update_manifest.json"
PROBE_NAME = "gxb_hotupdate_probe.lua"


def safe_version(value: str) -> str:
    """Validate the exact version grammar consumed by UpdateScene.compareVersion().

    The client splits the stored resource version on dots and calls tonumber() on
    the first three components.  Labels such as ``1.631.0-local1`` therefore
    crash the launcher on the next boot before MID2 is sent.  Keep the resource
    version strictly numeric and three-component.
    """
    value = value.strip()
    if not re.fullmatch(r"\d+\.\d+\.\d+", value):
        raise SystemExit(
            "--version must be exactly three numeric components (for example 1.631.1). "
            "GXB UpdateScene.compareVersion() cannot parse suffixes such as -local1."
        )
    return value


def iter_override_files():
    for tree_name in ("src_32", "src_64"):
        tree = LOCAL / tree_name
        if not tree.is_dir():
            continue
        for path in sorted(tree.rglob("*")):
            if not path.is_file():
                continue
            rel = path.relative_to(LOCAL)
            if path.name == "README.txt" or path.name.endswith(".gxb_v061_probe_original"):
                continue
            yield path, rel.as_posix()


def md5_file(path: Path) -> str:
    h = hashlib.md5()
    with path.open("rb") as fh:
        for block in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--version", required=True,
        help="numeric resource version stored by UpdateScene after install (exactly N.N.N; e.g. 1.631.1)",
    )
    ap.add_argument("--silent", action="store_true", help="source behavior: use is_review=1 so UpdateScene skips its confirmation dialog")
    ap.add_argument("--disable", action="store_true", help="build package but write manifest enabled=false")
    ap.add_argument("--probe-only", action="store_true", help="build only a harmless marker module in src_32/src_64 to validate MID2 download/unzip")
    args = ap.parse_args()

    version = safe_version(args.version)
    if args.probe_only:
        marker = (
            "-- Harmless GXB MID2 hot-update probe.\n"
            "return { marker = \"gxb_mid2_hotupdate_probe\", version = \"" + version + "\" }\n"
        )
        probe_files = []
        for tree_name in ("src_32", "src_64"):
            tree = LOCAL / tree_name
            tree.mkdir(parents=True, exist_ok=True)
            path = tree / PROBE_NAME
            path.write_text(marker, encoding="utf-8")
            probe_files.append((path, f"{tree_name}/{PROBE_NAME}"))
        files = probe_files
    else:
        files = list(iter_override_files())
    if not files:
        raise SystemExit("No override files found under local_assets/src_32 or local_assets/src_64")

    UPDATES.mkdir(parents=True, exist_ok=True)
    package = f"gxb-local-{version}.zip"
    volume = UPDATES / f"{package}.001"

    fd, tmp_name = tempfile.mkstemp(prefix="gxb-local-update-", suffix=".zip", dir=str(UPDATES))
    os.close(fd)
    tmp = Path(tmp_name)
    try:
        with zipfile.ZipFile(tmp, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
            for src, arcname in files:
                zf.write(src, arcname)
        tmp.replace(volume)
    finally:
        tmp.unlink(missing_ok=True)

    # Keep the backend-local update directory deterministic and avoid leaving
    # an obsolete/malformed probe volume that an operator could accidentally
    # serve by hand. Only files generated by this helper's gxb-local prefix are
    # removed.
    for stale in UPDATES.glob("gxb-local-*.zip.[0-9][0-9][0-9]"):
        if stale != volume:
            stale.unlink(missing_ok=True)

    size = volume.stat().st_size
    md5 = md5_file(volume)
    manifest = {
        "enabled": not args.disable,
        "version": version,
        "package": package,
        "volume": 1,
        "size": size,
        "md5": md5,
        "silent": bool(args.silent),
        "files": [arcname for _src, arcname in files],
        "probe_only": bool(args.probe_only),
        "note": "Generated from sparse backend-local src_32/src_64 overrides. Runtime lazy res files use /res/ separately.",
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"[LOCAL-UPDATE] files={len(files)}")
    print(f"[LOCAL-UPDATE] volume={volume}")
    print(f"[LOCAL-UPDATE] size={size} md5={md5}")
    print(f"[LOCAL-UPDATE] manifest={MANIFEST} enabled={manifest['enabled']} silent={manifest['silent']}")
    print("[LOCAL-UPDATE] restart server; MID2 advertises only while the client resource version is older")
    print("[LOCAL-UPDATE] do NOT use suffixes like -local1; UpdateScene.compareVersion() is numeric-only")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
